### PR TITLE
Added rotate plugin

### PR DESCRIPTION
**Pull request by danmasera**
It allows to rotate an image, according to any angle.
To do this, you  must call function caman.rotate(degrees), where
degrees must be a number (positive or negative, on depends if you
want that your image rotates in clockwise direction or
counterclockwise direction).
If degrees is a multiple of 90 canvas mantains the dimensions
of image, otherwise the canvas will become larger, with height and
width equals to the diagonal of the image.

### CODE REVIEW

**Comment by meltingice** [comment]
This is awesome, thanks!

**Comment by rulaszek** [comment]
I also agree this is awesome.  Hey, I have run into a strange intermittent issue with rotate where the image gets scrambled sometimes when I rotate.  I have attached a screenshot of the scrambled image.  Any ideas?  My users are intermittently seeing this but I haven't been able to reproduce it yet.

image

I pulled caman.full.js from trunk around 8/21 with the rotate plugin in it.

Any suggestions to whats happening here are greatly appreciated.

Thanks

**Comment by confile** [comment]
How do I have to use rotate? I use caman.full.pack.js and tried:

``` javascript
Caman("#canvasId", function () {
    his.rotate({
    degrees: 90
    });
});
```

But, this was not working.

**Comment by meltingice** [comment]
``` js
Caman("#canvasId", function () {
  this.rotate(90);
  this.render();
});
```

**Pull request merged**
